-- CRIAÇÃO DE TABELAS
CREATE TABLE TALUNO
(
    COD_ALUNO INTEGER NOT NULL,
    NOME VARCHAR(30),
    CIDADE VARCHAR2(30),
    CEP VARCHAR(30),
    PRIMARY KEY (COD_ALUNO)
);

CREATE TABLE TCONTRATO
(
    COD_CONTRATO INTEGER NOT NULL PRIMARY KEY,
    DATA DATE,
    COD_ALUNO INTEGER,
    TOTAL NUMBER(8,2),
    DESCONTO NUMBER(5,2)
);

-- POPULANDO TABELA TALUNO COM DADOS
INSERT INTO TALUNO VALUES(13101994, 'Kaio Cândido Santiago', 'Goverandor Valares', '84025290');
INSERT INTO TALUNO VALUES(30111990, 'Eliziane de Oilveira', 'Reserva', '84025290');
INSERT INTO TALUNO VALUES(3325235, 'Maria Cândida', 'Jampruca', '84025330');
INSERT INTO TALUNO VALUES(23523435, 'Jorge Felipe Santiago', 'Governador Valadares', '84025440');

-- POPULANDO TABELA TCONTRATO COM DADOS
INSERT INTO TCONTRATO VALUES(165, SYSDATE, 13101994, 500, 10);
INSERT INTO TCONTRATO VALUES(35234, SYSDATE - 1, 30111990, 350, 10);

-- CONCATENANDO STRINGS
SELECT NOME || ' ' || COD_ALUNO FROM TALUNO;

-- DEFININDO OUTPUT DA DATA
SELECT TO_CHAR(DATA, 'YYYYMMDD') FROM TCONTRATO;

-- PROCEDURE
CREATE OR REPLACE PROCEDURE P_create_table
AS 
    NUM_ROWS NUMBER;
BEGIN
    SELECT COUNT(*) INTO NUM_ROWS
    FROM TALUNO
    WHERE NOME = 'Kaio Cândido Santiago';
    
    IF NUM_ROWS = 0
    THEN
        EXECUTE IMMEDIATE 'INSERT INTO TALUNO VALUES(13101994, 
                            ESTRELA, 
                            Goverandor Valares, 
                            13);
                            ';
        DBMS_OUTPUT.put_line ('table created'); 
    ELSE
        DBMS_OUTPUT.put_line ('Table already exists');
    END IF;
END;
/

-- ADICIONANDO COLUNA EM UAM TABELA
ALTER TABLE TALUNO ADD ESTADO VARCHAR(30);

-- POPULANDO COLUNA ADICIONADA
UPDATE TALUNO SET ESTADO = 'MG' WHERE (NOME LIKE 'Kaio%' OR NOME LIKE 'Maria%' OR NOME LIKE 'Jorge%');
UPDATE TALUNO SET ESTADO = 'PR' WHERE NOME LIKE 'Elizi%';

-- USANDO CASE E WHEN
SELECT NOME, CIDADE, ESTADO,
CASE 
   WHEN ESTADO = 'MG' THEN 'MINEIRO'
   WHEN ESTADO = 'PR' THEN 'PARANAENSE'
   ELSE 'OUTRO'
END
FROM TALUNO;